### ISSUE TITLE
No such file or directory @ rb_sysopen - example.doc (Errno::ENOENT)

### ISSUE THREAD

**Issue by jhonc33** [documentcloud/docsplit#115]
Hi, i'm trying to extract images from a Microsoft Office Word document and return this error:

```
/home/deploy/.rvm/gems/ruby-2.1.2/gems/docsplit-0.7.5/lib/docsplit/transparent_pdfs.rb:22:in `initialize': No such file or directory @ rb_sysopen - example.doc (Errno::ENOENT)
from /home/deploy/.rvm/gems/ruby-2.1.2/gems/docsplit-0.7.5/lib/docsplit/transparent_pdfs.rb:22:in `open'
from /home/deploy/.rvm/gems/ruby-2.1.2/gems/docsplit-0.7.5/lib/docsplit/transparent_pdfs.rb:22:in `is_pdf?'
from /home/deploy/.rvm/gems/ruby-2.1.2/gems/docsplit-0.7.5/lib/docsplit/transparent_pdfs.rb:11:in `block in ensure_pdfs'
from /home/deploy/.rvm/gems/ruby-2.1.2/gems/docsplit-0.7.5/lib/docsplit/transparent_pdfs.rb:10:in `map'
from /home/deploy/.rvm/gems/ruby-2.1.2/gems/docsplit-0.7.5/lib/docsplit/transparent_pdfs.rb:10:in `ensure_pdfs'
from /home/deploy/.rvm/gems/ruby-2.1.2/gems/docsplit-0.7.5/lib/docsplit.rb:50:in `extract_images'
from test.rb:4:in `<main>'
```

This is the script:

```
require "docsplit"
Docsplit.extract_images('example.doc', :size => '1000x', :format => [:png, :jpg])
```

I'm using Centos 6 with all libraries installed, on Mac Os X works great on the same way.
If i try to convert a pdf works great, only fail with office documents.

Any ideas?

Thanks,

**Comment by crusadergo** [comment]
up

**Comment by thanhtoan1196** [comment]
up
